# Generated by Django 6.1.1 on 2026-09-25 19:41

import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[users.validators.validate_age]),
        ),
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=models.TextField(blank=True, help_text='Увлечения через запятую', validators=[users.validators.validate_no_contacts]),
        ),
    ]
